# messages
USER_EXISTS = "User with {username} is already exists. Please check inbox."
USER_CREATED = "User: {username} created Successfully. Id : {id}"
USER_UPDATED = "User : {username}'s data is updated successfully."
INVALID_DETAILS_FORMAT = "Please enter details with proper format"
INVALID_USERNAME_FORMAT = "Invalid Username format."
INVALID_PASSWORD_FORMAT = "Invalid Password format."
INVALID_EMAIL_FORMAT = "Invalid Email format."
FIELDS_MISSING = "Fields Missing."
SOMETHING_WENT_WRONG = "Something Went Wrong."
ACCOUNT_DISABLED = "Your account is disabled. Please contact to Administrator."
INVALID_CREDENTIALS = "Invalid Username or Password. Please Try Again."
USER_DOES_NOT_EXIST = "User doesn't exist with id: {id}"
YOU_CAN_NOT_UPDATE = ".So,You can't update."

# Regex
PASSWORD_PATTERN = "^(?!.*\s)(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{10,}$"
USERNAME_PATTERN = "^(?!.*\s)(?=.*[a-z])[a-z0-9]{7,30}$"
EMAIL_PATTERN = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}$"
MOBILE_NUMBER_PATTERN = "[0-9]{10}"
